FROM eclipse-temurin:17-jre

WORKDIR /app
COPY --chown=10001:10001 narration-service/target/narration-service-0.1.0.jar /app/app.jar

USER 10001:10001
EXPOSE 8082
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75.0", "-jar", "/app/app.jar"]
