version: '3.8'

services:
  # 1. Cơ sở dữ liệu dùng chung (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: sgu_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: narration_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # 2. Message Broker (RabbitMQ kèm giao diện quản lý UI)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sgu_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    ports:
      - "5672:5672"   # Port để code giao tiếp
      - "15672:15672" # Port mở giao diện UI trên trình duyệt
    volumes:
      - mqdata:/var/lib/rabbitmq
    restart: unless-stopped

  # 3. Object Storage (MinIO - Giả lập AWS S3 để lưu MP3)
  minio:
    image: minio/minio
    container_name: sgu_minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # Port API
      - "9001:9001"   # Port giao diện Console
    volumes:
      - miniodata:/data
    restart: unless-stopped

volumes:
  pgdata:
  mqdata:
  miniodata: